### ISSUE TITLE
Package names are wrong...

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/qc-metrics#2]
The packages are `org.bdgenomics.adam`

**Comment by fnothaft** [comment]
OK, so, since we pointed at the 0.16.0 release, this repository is a bit scoobied. I'll take more of a deep dive into this tomorrow.

**Comment by tdanford** [comment]
Hmmmm?  What should the package names be?  I thought I was working off of ``master`` in adam.

**Comment by fnothaft** [comment]
@tdanford they're the correct names for packages in _ADAM_ ;). I'm suggesting `s/org.bdgenomics.adam/org.bdgenomics.qc/g`.

**Comment by fnothaft** [comment]
I'll have a PR tomorrow AM for this. I think the PR will clarify.
