### ISSUE TITLE
Release a v0.0.1

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/qc-metrics#4]
We have some things in Guacamole that depend on this and it's a little awkward to have to just point at the Maven snapshot that is the only artifact that exists, afaict.

**Comment by fnothaft** [comment]
SGTM; I can do that tomorrow.

**Comment by fnothaft** [comment]
I've released Scala [2.10](https://github.com/bigdatagenomics/qc-metrics/tree/qc-metrics-parent_2.10-0.0.1) and [2.11](https://github.com/bigdatagenomics/qc-metrics/tree/qc-metrics-parent_2.11-0.0.1) versions of qc-metrics. They've been promoted in Sonatype, so I'd expect them to show up sometime late this afternoon.

**Comment by ryan-williams** [comment]
thanks a lot @fnothaft !
